#!/bin/sh

# Protein
P=($(<protein.txt))

# Mutation
m=0.025 

# Crossover
c=0.90  

# Energy evaluations
e=1000  

# Minimun energy
m=-40  

# Population sizes
s=(16 32 64 128 256 512 1024)

# Bootstrap
PARENT=$(pwd)
LOG=$PARENT/log

mkdir log

rm $LOG/*

make all

for i in "${!s[@]}"; do
    # Compile code
    echo "Compiling with vectorization (Population = $i)"

    # Execute code
    echo "Executing code"
    ./hpfolder -e $e -y $m -p $P -s $i -m $m -c $c 

    # Analysis with gprof
    OUTPUT_GPROF=$LOG/gprof_$i.txt
    echo "Profiling in progress"
    gprof --ignore-non-functions ./hpfolder > $OUTPUT_GPROF

    # Analysis with gprof2dot
    echo "Generating graph"
    gprof2dot -s -w -n0 -e0 -z "calculation(Population*)" $OUTPUT_GPROF | dot -Tpng -o $LOG/graph_calc_$i.png
    gprof2dot -s -w -n0 -e0 -z "Population::Population(int, Protein, float, float)" $OUTPUT_GPROF | dot -Tpng -o $LOG/graph_pop_$i.png

    printf "\n"
done

echo "Finished"