#!/bin/sh

# Protein
P=WWBWWBBWWBBWWWWWBBBBBBBBBBWWWWWWBBWWBBWWBWWBBBBB

# Mutation
m=0.025 

# Crossover
c=0.90  

# Energy evaluations
e=1000  

# Minimun energy
y=-23   

# Population size
s=128

# Make program
make all

# Executing code
./hpfolder -e $e -y $y -p $P -s $s -m $m -c $c 

# Destroy it
make clean