#!/bin/sh

# Protein
P=BBBBWWWWBBBBBBBBBBBBWWWWWWBBBBBBBBBBBBWWWBBBBBBBBBBBBWWWBBBBBBBBBBBBWWWBWWBBWWBBWWBWB

# Mutation
m=0.025 

# Crossover
c=0.90  

# Energy evaluations
e=10000

# Minimun energy
y=-52   

# Population size
s=256

# Make program
make all

# Executing code
./hpfolder -e $e -y $y -p $P -s $s -m $m -c $c 

# Destroy it
# make clean