#!/bin/bash
#SBATCH --partition=amd-512
#SBATCH --job-name=hpfolder
#SBATCH --output=hpfolder-%j.out
#SBATCH --error=hpfolder-%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --time=0-0:10

# Protein
P=WWBWWBBWWBBWWWWWBBBBBBBBBBWWWWWWBBWWBBWWBWWBBBBB

# Mutation
m=0.025 

# Crossover
c=0.90  

# Energy evaluations
e=1000  

# Minimun energy
m=-23   

# Population size
s=128

./hpfolder -e $e -y $m -p $P -s $s -m $m -c $c 